config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users
  resources :users, only: [:show]

  resources :tweets do
  resources :likes, only: [:create, :destroy]

  end

  root 'tweets#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id

end

app/models/tag.rb
class Tag < ApplicationRecord

validates :name, presence: true
  
has_many :tweet_tag_relations, dependent: :destroy

has_many :tweets, through: :tweet_tag_relations, dependent: :destroy

end

app/models/tweet.rb
class Tweet < ApplicationRecord
belongs_to :user

has_many :likes, dependent: :destroy
has_many :liked_users, through: :likes, source: :user

has_one_attached :image

has_many :tweet_tag_relations, dependent: :destroy

has_many :tags, through: :tweet_tag_relations, dependent: :destroy

end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :tweets, dependent: :destroy 
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 }

  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet

   def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 
  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) 
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

before_action :authenticate_user!, only: [:new, :create]

 def index
   @tweets = Tweet.all

   if params[:tag_ids]
      @tweets = []
      params[:tag_ids].each do |key, value|      
        @tweets += Tag.find_by(name: key).tweets if value == "1"
      end
      @tweets.uniq!
    end

    if params[:tag]
      Tag.create(name: params[:tag])
    end

  end
 

 def new
    @tweet = Tweet.new
  end

 def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end


  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

 def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

 def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private

  def tweet_params
    params.require(:tweet).permit(:namae, :shozaichi, :taizaijikan, :eigyojikan, :idoujikan, :ryokin, :gaiyo, :image, tag_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
    @user = User.find(params[:id]) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tripplan" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
  <h1>TripPlan</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
   <footer>
      a
    </footer>
  </body>
  
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  
     <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :namae, :size => 30 %>
  </div>


  <div class="field">
    <%= f.label :所在地 %>
    <%= f.text_field :shozaichi, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :滞在時間 %>
    <%= f.text_field :taizaijikan, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :営業時間  %>
    <%= f.number_field :eigyojikan, :size => 10 %>
  </div>

  <div class="field">
    <%= f.label :移動時間 %>
    <%= f.text_field :idoujikan, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :料金 %>
    <%= f.text_field :ryokin, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :概要  %>
    <%= f.text_area :gaiyo, :size => "30x2" %>
  </div>

 <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h1>TripPlan</h1>
<h3>一覧ページ</h3>


<%= link_to "新規登録へ", new_tweet_path %>

<div class="tweets-container">


<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>


<% @tweets.each do |t| %>

 <%= link_to t.user.name, user_path(t.user.id) %>   

    <div class="tweet">
    <%= t.user.email %>

      <%= t.namae %>
      <%= t.shozaichi %>
      <%= t.taizaijikan %>
      <%= t.eigyojikan %>
      <%= t.idoujikan %>
      <%= t.ryokin %>
      <%= t.gaiyo %>


<% if t.image.attached? %>
     <%= image_tag t.image, size: '250x200'%>

<% end %>     

<% if user_signed_in? %>
<% if current_user.already_liked?(t) %>
 <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), data: { turbo_method: :delete } do %>
  <p>いいねを取り消す</p><%= t.likes.count %>
<% end %>
<% else %>
 <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), data: { turbo_method: :post }  do %>
  <p>いいね</p><%= t.likes.count %>
<% end %>
<% end %>
<% else %>
  <p>いいねの数 = </p><%= t.likes.count %>
<% end %>

 <%= t.created_at %>
 <%= link_to "詳細へ", tweet_path(t.id) %>
 <% if user_signed_in? && current_user.id == t.user_id %>
    <%= link_to "編集する", edit_tweet_path(t.id) %>
    <%= link_to "削除する", tweet_path(t.id), data: { turbo_method: :delete } %>
<% end %>
</div>

<% end %>
</div>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <% Tag.all.each do |t| %>
        <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
<% end %>
    <%= submit_tag '検索' %>
<% end %>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
<% end %>

app/views/tweets/new.html.erb
<h1>(TripPlan)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>


  <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :namae, :size => 30 %>
  </div>


  <div class="field">
    <%= f.label :所在地 %>
    <%= f.select :shozaichi, 
    [["あわら市", "あわら市"], 
    ["池田町", "池田町"], 
    ["永平寺町", "永平寺町"], 
    ["越前市", "越前市"], 
    ["越前町", "越前町"], 
    ["おおい町", "おおい町"], 
    ["大野市", "大野市"], 
    ["小浜市", "小浜市"], 
    ["勝山市", "勝山市"], 
    ["坂井市", "坂井市"], 
    ["鯖江市", "鯖江市"], 
    ["高浜町", "高浜町"], 
    ["敦賀市", "敦賀市"], 
    ["福井市", "福井市"], 
    ["南越前町", "南越前町"], 
    ["美浜町", "美浜町"], 
    ["若狭町", "若狭町"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :滞在時間 %>
    <%= f.text_field :taizaijikan, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :営業時間  %>
    <%= f.text_field :eigyojikan, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :移動時間 %>
    <%= f.text_field :idoujikan, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :料金 %>
    <%= f.text_field :ryokin, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :概要  %>
    <%= f.text_area :gaiyo, :size => "30x2" %>
  </div>

 <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

 <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
 <div class='form-check'>
    <%= tag.label class: 'form-check-label' do %>
    <%= tag.check_box class: 'form-check-input' %>
    <%= tag.text %>
    <% end %>
  </div>
    <% end %>
  </div>


  <%= f.submit "登録する" %>
<% end %>

<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>TripPlan</h1>

<h3>登録詳細</h3>
<div class="tweet">
  <p><%= @tweet.namae %></p>
  <p><%= @tweet.shozaichi %></p>
  <p><%= @tweet.taizaijikan %></p>
  <p><%= @tweet.eigyojikan %></p>
  <p><%= @tweet.idoujikan %></p>
  <p><%= @tweet.ryokin %></p>
  <p><%= @tweet.gaiyo %></p>
  <p><%= @tweet.created_at %></p>

<% if user_signed_in? %>
  <% if current_user.already_liked?(@tweet) %>
    <%= link_to tweet_like_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :delete } do %>
      <p>いいねを取り消す</p><%= @tweet.likes.count %>
<% end %>
<% else %>
    <%= link_to tweet_likes_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :post }  do %>
      <p>いいね</p><%= @tweet.likes.count %>
<% end %>
<% end %>
<% else %>
      <p>いいねの数 = </p><%= @tweet.likes.count %>
<% end %>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>

<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.namae %>
  <%= t.shozaichi %>
  <%= t.taizaijikan %>
  <%= t.eigyojikan %>
  <%= t.idoujikan %>
  <%= t.ryokin %>
  <%= t.gaiyo %>


<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.namae %>
  <%= t.shozaichi %>
  <%= image_tag t.image, size: '120x100'%>
<% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>